name: Build docker image

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true


jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - run: docker build -t ${{ github.event.pull_request.head.ref }} .
        name: build image

      - name: tag image
        run: docker tag ${{ github.event.pull_request.head.ref }}:latest 123567778292.dkr.ecr.eu-central-1.amazonaws.com:${{ github.event.pull_request.head.ref }}

      - name: push image
        run: docker push 123567778292.dkr.ecr.eu-central-1.amazonaws.com:${{ github.event.pull_request.head.ref }}

