name: Reusable ECR Docker Workflow

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        default: 'eu-central-1'
        type: string
        description: 'AWS Region'
      ecr-url:
        required: true
        description: 'ECR URL'
        type: string
      app-name:
        required: true
        description: 'App Name'
        type: string
      branch-name:
        required: true
        description: 'Branch name'
        type: string
      env:
        required: true
        description: 'Environment'
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deployAppToK8s:
    name: Deploy App to K8s
    runs-on: ubuntu-latest
    container:
        image: public.ecr.aws/d1z6e0p1/celebrate-deployment:latest

    environment: ${{inputs.env}}
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: echo
        run: echo ${{ inputs.branch-name }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Release app
        run: |
          helm repo add celebrate https://omarsh1996.github.io/celebrate-deployment/
          helm repo update
          aws eks update-kubeconfig --name eksdemo1
      - name:  Helm Release app
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
        run: |
          helm upgrade --install celebrate-deployment-${{ inputs.app-name }} -f .github/.values.yaml celebrate/celebrate-deployment --set appName=${{ inputs.app-name }} --set prefix=${{ inputs.app-name }} --set image.tag=${{ inputs.branch-name }} --set jwtSecretData.SECRET1=${{ secrets.K8S_APP_SECRET1 }} --set jwtSecretData.VAR=${{ secrets.K8S_APP_VAR }} --set jwtSecretData.SECRET1=${{ secrets.K8S_APP_SECRET1 }} --namespace $(echo ${{ github.repository }} | cut -d'/' -f2) --create-namespace
