name: Reusable ECR Docker Workflow

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        default: 'eu-central-1'
        type: string
        description: 'AWS Region'
      ecr-url:
        required: true
        description: 'ECR URL'
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deployAppToK8s:
    name: Deploy App to K8s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Release app
        run: |
          helm repo add omarsh1996 https://omarsh1996.github.io/celebrate-deployment/
          helm repo update
          aws eks update-kubeconfig --name eksdemo1
          helm upgrade --install celebrate-deployment-${{ github.event.pull_request.head.ref }} omarsh1996/celebrate-deployment --set appName=${{ github.event.pull_request.head.ref }} --set prefix=${{ github.event.pull_request.head.ref }}
          kubectl rollout restart deployment celebrate-deployment-${{ github.event.pull_request.head.ref }}