name: Main Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  useReusableWorkflow:
    uses: ./.github/workflows/build-image.yaml
    with:
      aws-region: 'eu-central-1'
      ecr-url: '123567778292.dkr.ecr.eu-central-1.amazonaws.com'
      ecr-repo-name: 'k8s-example-app'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
