name: Main Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  buildImage:
    uses: ./.github/workflows/build-image.yaml
    with:
      aws-region: 'eu-central-1'
      ecr-url: ${{vars.IMAGE_REPO}}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  DEPLOY_FEATURE:
    needs: buildImage
    uses: ./.github/workflows/deploy-app.yaml
    with:
      aws-region: 'eu-central-1'
      ecr-url: ${{vars.IMAGE_REPO}}
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}