name: Main Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  print:
    name: 'RRR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Print PR number'
        run: echo "PR number is ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  build:
    uses: ./.github/workflows/build-image.yaml
    with:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
