name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build-image.yaml
    with:
      IMAGE_REPO: ${{ env.IMAGE_REPO }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}