name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployToStage:
        description: 'Deploy to stage manually?'
        required: true
        default: 'no'


jobs:
  BUILD_IMAGE:
    name: Build image
    uses: omarsh1996/reusable-workflows/.github/workflows/build-image.yaml@main
    with:
      aws-region: 'eu-central-1'
      ecr-url: ${{vars.IMAGE_REPO}}
      branch-name: main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  RUN_TESTS:
    needs: BUILD_IMAGE
    name: Run tests
    uses: ./.github/workflows/run-tests.yaml

  DEPLOY_TO_STAGE:
    name: Deploy to stage
    needs: RUN_TESTS
    uses: omarsh1996/reusable-workflows/.github/workflows/deploy-app.yaml@main
    with:
      aws-region: 'eu-central-1'
      ecr-url: ${{vars.IMAGE_REPO}}
      app-name: stage
      env: Stage
      branch-name: main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  tag_major:
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Bump Major Version
        run: npm run major
      - name: Push Major Tag
        run: git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: echo ${{ github.token }}
        env:
         GITHUB_TOKEN: ${{ github.token }}
  tag_minor:
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Bump Minor Version
        run: npm run minor
      - name: Push Minor Tag
        run: git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag_patch:
    environment: Stage
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Bump Patch Version
        run: npm run patch
      - name: Push Patch Tag
        run: git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}