name: PR Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployToStage:
        description: 'Deploy to stage manually?'
        required: true
        default: 'no'

jobs:
  BUILD_IMAGE:
    name: Build image
    uses: omarsh1996/reusable-workflows/.github/workflows/build-image.yaml@main
    with:
      aws-region: 'eu-central-1'
      ecr-url: ${{vars.IMAGE_REPO}}
      branch-name: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.event_name == 'workflow_dispatch' && github.ref_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  RUN_TESTS:
    name: Run tests
    uses: ./.github/workflows/run-tests.yaml

  DEPLOY_FEATURE:
    name: Deploy feature
    needs: BUILD_IMAGE
    uses: omarsh1996/reusable-workflows/.github/workflows/deploy-app.yaml@main
    with:
      aws-region: 'eu-central-1'
      ecr-url: ${{vars.IMAGE_REPO}}
      app-name: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.event_name == 'workflow_dispatch' && github.ref_name }}
      branch-name: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.event_name == 'workflow_dispatch' && github.ref_name }}
      env: feature
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  DEPLOY_TO_STAGE:
    name: Deploy to stage
    needs: DEPLOY_FEATURE
    uses: omarsh1996/reusable-workflows/.github/workflows/deploy-app.yaml@main
    with:
      aws-region: 'eu-central-1'
      ecr-url: ${{vars.IMAGE_REPO}}
      app-name: stage
      env: Stage
      branch-name: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.event_name == 'workflow_dispatch' && github.ref_name }}

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
