name: Version Tag Workflow

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}


jobs:
  BUILD_IMAGE:
    name: Build image
    uses: omarsh1996/reusable-workflows/.github/workflows/build-image.yaml@main
    with:
      aws-region: 'eu-central-1'
      ecr-url: ${{vars.IMAGE_REPO}}
      branch-name: ${{ github.ref/refs/tags/ }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}






